on:
  push:
    branches:
      - master
  workflow_dispatch:

name: 🚀 Deploy CRMS App

jobs:
  deploy:
    name: 🎉 CRMS Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      # FRONTEND
      - name: 📦 Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: 🛠 Build React app
        working-directory: frontend
        run: npm run build

      - name: 📂 Upload frontend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.thelemaschool.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /html.thelemaschool.com/
          local-dir: frontend/dist/

      # BACKEND
      - name: 📦 Install backend dependencies
        working-directory: backend
        run: npm install

      - name: 🛠 Build backend app
        working-directory: backend
        run: npm run build

      - name: 📂 Upload backend `dist/` via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.thelemaschool.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /api.thelemaschool.com/
          local-dir: backend/dist/

      - name: 🧼 Prepare tmp directory with fresh restart.txt
        working-directory: backend
        run: |
          mkdir -p tmp
          date > tmp/restart.txt


      - name: 📂 restart trigger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.thelemaschool.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /api.thelemaschool.com/tmp/
          local-dir: backend/tmp/